#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""ROM-free regression for H8/3003 interrupt-controller boundary semantics.

This extracts the production INTC methods into a minimal C++ harness.  It
checks IPRA/IPRB byte writes and the H8/3003 manual section 5.5.1 rule that an
IRQ coincident with the CPU instruction clearing its enable or flag remains
eligible at that instruction's completion.  It is not a silicon pin-phase
oracle and does not cover internal peripheral enable/flag registers.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


class TestFailure(RuntimeError):
    """A regression contract was not satisfied."""


def extract_method(source: str, qualified_name: str) -> str:
    match = re.search(
        rf"(?m)^[^\n]*\b{re.escape(qualified_name)}\s*\([^\n]*\)\s*(?:const\s*)?\{{",
        source,
    )
    if not match:
        raise TestFailure(f"production method not found: {qualified_name}")

    start = match.start()
    opening = source.find("{", match.start(), match.end())
    depth = 0
    in_string: str | None = None
    escaped = False
    line_comment = False
    block_comment = False
    index = opening
    while index < len(source):
        char = source[index]
        following = source[index + 1] if index + 1 < len(source) else ""
        if line_comment:
            line_comment = char != "\n"
            index += 1
            continue
        if block_comment:
            if char == "*" and following == "/":
                block_comment = False
                index += 2
            else:
                index += 1
            continue
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            index += 1
            continue
        if char == "/" and following == "/":
            line_comment = True
            index += 2
            continue
        if char == "/" and following == "*":
            block_comment = True
            index += 2
            continue
        if char in {'"', "'"}:
            in_string = char
            index += 1
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return source[start : index + 1]
        index += 1
    raise TestFailure(f"unterminated production method: {qualified_name}")


def extract_table(source: str, declaration: str) -> str:
    start = source.find(declaration)
    if start < 0:
        raise TestFailure(f"production table not found: {declaration}")
    end = source.find("};", start)
    if end < 0:
        raise TestFailure(f"unterminated production table: {declaration}")
    return source[start : end + 2]


def make_shim(intc_cpp: str) -> str:
    methods = "\n\n".join(
        extract_method(intc_cpp, name)
        for name in (
            "h8_intc_device::internal_interrupt",
            "h8_intc_device::set_filter",
            "h8_intc_device::ier_r",
            "h8_intc_device::ier_w",
            "h8_intc_device::instruction_boundary",
            "h8_intc_device::check_level_irqs",
            "h8_intc_device::update_irq_state",
            "h8_intc_device::get_priority",
            "h8h_intc_device::isr_r",
            "h8h_intc_device::isr_w",
            "h8h_intc_device::icr_r",
            "h8h_intc_device::icr_w",
            "h8h_intc_device::get_priority",
        )
    )
    vector_table = extract_table(
        intc_cpp, "const int h8h_intc_device::vector_to_slot[64]"
    )

    return f"""// Generated by h83003_intc_state_test.py.
#include <cstdint>
#include <cstdio>
#include <cstring>

using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using offs_t = std::uint32_t;

#define logerror(...) ((void)0)

class cpu_stub
{{
public:
    bool dma_access = false;
    int vector = -1;
    int level = -2;
    bool nmi = false;
    int updates = 0;

    bool access_is_dma() const {{ return dma_access; }}
    bool trigger_dma(int) {{ return false; }}
    void set_irq(int irq_vector, int irq_level, bool irq_nmi)
    {{
        vector = irq_vector;
        level = irq_level;
        nmi = irq_nmi;
        updates++;
    }}
}};

class cpu_ref
{{
public:
    explicit cpu_ref(cpu_stub &cpu) : m_cpu(&cpu) {{ }}
    cpu_stub *operator->() {{ return m_cpu; }}
    const cpu_stub *operator->() const {{ return m_cpu; }}
private:
    cpu_stub *m_cpu;
}};

class h8_intc_device
{{
public:
    enum {{ LEVEL_LOW, EDGE_FALL, EDGE_RISE, EDGE_DUAL }};
    enum {{ MAX_VECTORS = 256 }};

    explicit h8_intc_device(cpu_stub &cpu) : m_cpu(cpu)
    {{
        std::memset(m_pending_irqs, 0, sizeof(m_pending_irqs));
        std::memset(m_irq_type, 0, sizeof(m_irq_type));
    }}
    virtual ~h8_intc_device() = default;

    int m_irq_vector_base = 12;
    int m_irq_vector_count = 8;
    int m_irq_vector_nmi = 7;
    bool m_has_isr = true;
    cpu_ref m_cpu;
    u32 m_pending_irqs[MAX_VECTORS / 32];
    u8 m_irq_type[8];
    u8 m_nmi_type = EDGE_FALL;
    bool m_nmi_input = false;
    u8 m_irq_input = 0;
    u8 m_ier = 0;
    u8 m_isr = 0;
    u16 m_iscr = 0;
    int m_icr_filter = 0;
    int m_ipr_filter = -1;
    bool m_instruction_boundary_clear = true;
    u8 m_boundary_ier = 0;
    u8 m_boundary_isr = 0;

    void internal_interrupt(int vector);
    void set_filter(int icr_filter, int ipr_filter);
    u8 ier_r();
    void ier_w(u8 data);
    void instruction_boundary();
    void check_level_irqs(bool update);
    void update_irq_state();
    virtual void get_priority(int vect, int &icr_pri, int &ipr_pri) const;
}};

class h8h_intc_device : public h8_intc_device
{{
public:
    explicit h8h_intc_device(cpu_stub &cpu) : h8_intc_device(cpu) {{ }}
    static const int vector_to_slot[64];
    u32 m_icr = 0;

    u8 isr_r();
    void isr_w(u8 data);
    u8 icr_r(offs_t offset);
    void icr_w(offs_t offset, u8 data);
    void get_priority(int vect, int &icr_pri, int &ipr_pri) const override;
}};

{methods}

{vector_table}

static int failures = 0;

template <typename Actual, typename Expected>
void expect_eq(const char *label, Actual actual, Expected expected)
{{
    if (actual != expected)
    {{
        std::fprintf(stderr, "FAIL %-48s actual=%lld expected=%lld\\n", label,
            static_cast<long long>(actual), static_cast<long long>(expected));
        failures++;
    }}
}}

void clear_requests(h8h_intc_device &intc)
{{
    std::memset(intc.m_pending_irqs, 0, sizeof(intc.m_pending_irqs));
    intc.m_ier = intc.m_isr = 0;
    intc.m_boundary_ier = intc.m_boundary_isr = 0;
    intc.m_icr = 0;
    intc.set_filter(0, -1);
}}

int main()
{{
    cpu_stub cpu;
    h8h_intc_device intc(cpu);

    // Two independently addressable IPRA/IPRB bytes must survive writes to
    // the other address.
    intc.icr_w(0, 0x08);
    intc.icr_w(1, 0xa5);
    expect_eq("IPRB write preserves IPRA", intc.m_icr, u32(0x0000a508));
    intc.icr_w(0, 0x80);
    expect_eq("IPRA write preserves IPRB", intc.m_icr, u32(0x0000a580));

    // A priority write must immediately recompute the selected vector.
    clear_requests(intc);
    intc.m_ier = intc.m_isr = 0x01;
    intc.m_pending_irqs[0] = u32(1) << 20;
    intc.update_irq_state();
    expect_eq("reset priority chooses lower vector", cpu.vector, 12);
    const int updates_before_icr = cpu.updates;
    intc.icr_w(0, 0x08); // IPRA3 raises vector 20's module priority.
    expect_eq("IPRA write recomputes winning vector", cpu.vector, 20);
    expect_eq("IPRA write emitted one recomputation", cpu.updates,
        updates_before_icr + 1);

    // Clearing IRQ1E changes readback now, but not this instruction's final
    // arbitration.  The boundary call occurs after the CPU snapshots vector 13.
    clear_requests(intc);
    intc.m_ier = intc.m_isr = 0x02;
    intc.update_irq_state();
    expect_eq("IRQ1 pending before IER clear", cpu.vector, 13);
    intc.ier_w(0x00);
    expect_eq("IER clear has immediate readback", intc.ier_r(), 0x00);
    expect_eq("IER clear preserves completion eligibility", cpu.vector, 13);
    const int selected_at_completion = cpu.vector;
    intc.instruction_boundary();
    expect_eq("CPU snapshots held IRQ at completion", selected_at_completion, 13);
    expect_eq("IER clear applies after instruction boundary", cpu.vector, 0);

    // An edge delivered by the scheduler after the mapped write still sees
    // the enable state that was active during the write cycle.
    clear_requests(intc);
    intc.m_ier = 0x02;
    intc.ier_w(0x00);
    intc.m_isr |= 0x02;
    intc.update_irq_state();
    expect_eq("coincident post-write IRQ sees old IER", cpu.vector, 13);
    intc.instruction_boundary();
    expect_eq("coincident IRQ hold expires at boundary", cpu.vector, 0);

    clear_requests(intc);
    intc.m_ier = intc.m_isr = 0x02;
    intc.update_irq_state();
    intc.isr_w(0x00);
    expect_eq("ISR clear has immediate readback", intc.isr_r(), 0x00);
    expect_eq("ISR clear preserves completion eligibility", cpu.vector, 13);
    intc.instruction_boundary();
    expect_eq("ISR clear applies after instruction boundary", cpu.vector, 0);

    // A masked request is not accepted at the clear boundary and must not
    // reappear when the CPU later unmasks it.
    clear_requests(intc);
    intc.m_ier = intc.m_isr = 0x02;
    intc.set_filter(2, -1);
    expect_eq("low-priority IRQ masked before clear", cpu.vector, 0);
    intc.isr_w(0x00);
    expect_eq("masked clear does not invent eligibility", cpu.vector, 0);
    intc.instruction_boundary();
    intc.set_filter(0, -1);
    expect_eq("masked cleared IRQ does not reappear", cpu.vector, 0);

    // A higher-priority request wins at completion; the held lower request is
    // discarded after the boundary as section 5.5.1 specifies.
    clear_requests(intc);
    intc.m_icr = 0x08; // vector 20 priority 1, external IRQ1 priority 0.
    intc.m_ier = intc.m_isr = 0x02;
    intc.update_irq_state();
    intc.isr_w(0x00);
    intc.internal_interrupt(20);
    expect_eq("higher-priority coincident request wins", cpu.vector, 20);
    intc.instruction_boundary();
    expect_eq("lower clear hold expires behind winner", cpu.vector, 20);

    // DMA writes are not CPU instructions and therefore do not acquire the
    // CPU-instruction completion hold.
    clear_requests(intc);
    intc.m_ier = intc.m_isr = 0x02;
    intc.update_irq_state();
    cpu.dma_access = true;
    intc.ier_w(0x00);
    expect_eq("DMA IER clear is immediate", cpu.vector, 0);

    if (failures)
        return 1;
    std::puts("PASS: H8/3003 IPRA/IPRB byte preservation and priority recomputation");
    std::puts("PASS: H8/3003 external IRQ enable/flag clear instruction-boundary race");
    return 0;
}}
"""


def check_boundary_wiring(root: Path) -> None:
    h8_cpp = (root / "src/devices/cpu/h8/h8.cpp").read_text(encoding="utf-8")
    h8_h = (root / "src/devices/cpu/h8/h8.h").read_text(encoding="utf-8")
    h83003_cpp = (root / "src/devices/cpu/h8/h83003.cpp").read_text(
        encoding="utf-8"
    )
    h83003_h = (root / "src/devices/cpu/h8/h83003.h").read_text(
        encoding="utf-8"
    )
    intc_cpp = (root / "src/devices/cpu/h8/h8_intc.cpp").read_text(
        encoding="utf-8"
    )

    if "virtual void interrupt_instruction_boundary();" not in h8_h:
        raise TestFailure("generic H8 instruction-boundary hook declaration is missing")
    if "virtual void interrupt_instruction_boundary() override;" not in h83003_h:
        raise TestFailure("H8/3003 instruction-boundary override is missing")
    if "m_intc->set_instruction_boundary_clear(true);" not in h83003_cpp:
        raise TestFailure("H8/3003 INTC boundary-clear mode is not configured")

    override = extract_method(
        h83003_cpp, "h83003_device::interrupt_instruction_boundary"
    )
    if "m_intc->instruction_boundary();" not in override:
        raise TestFailure("H8/3003 boundary hook does not release INTC clear holds")

    normal = extract_method(h8_cpp, "h8_device::prefetch_done")
    selection = normal.find("else if(m_irq_vector)")
    snapshot = normal.find("take_interrupt();", selection)
    boundary = normal.find("interrupt_instruction_boundary();", snapshot)
    if not 0 <= selection < snapshot < boundary:
        raise TestFailure(
            "normal instruction completion must snapshot IRQ before releasing clear holds"
        )
    for method_name in (
        "h8_device::prefetch_done_noirq",
        "h8_device::prefetch_done_noirq_notrace",
    ):
        definition = extract_method(h8_cpp, method_name)
        if definition.count("interrupt_instruction_boundary();") != 1:
            raise TestFailure(f"{method_name} does not release exactly one clear hold")

    required_state_tokens = (
        "save_item(NAME(m_boundary_ier));",
        "save_item(NAME(m_boundary_isr));",
        "m_boundary_ier = m_boundary_isr = 0x00;",
    )
    missing = [token for token in required_state_tokens if token not in intc_cpp]
    if missing:
        raise TestFailure("INTC boundary state is not save/reset complete: " + ", ".join(missing))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="MAME source root",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    intc_cpp = (root / "src/devices/cpu/h8/h8_intc.cpp").read_text(
        encoding="utf-8"
    )

    check_boundary_wiring(root)
    compiler = shutil.which("c++") or shutil.which("clang++") or shutil.which("g++")
    if not compiler:
        raise TestFailure("no C++ compiler found")
    with tempfile.TemporaryDirectory(prefix="h83003-intc-") as temp_name:
        temp = Path(temp_name)
        source = temp / "h83003_intc_test.cpp"
        binary = temp / "h83003_intc_test"
        source.write_text(make_shim(intc_cpp), encoding="utf-8")
        compile_result = subprocess.run(
            [compiler, "-std=c++17", "-Wall", "-Wextra", "-Werror", str(source), "-o", str(binary)],
            cwd=root,
            check=False,
            text=True,
            capture_output=True,
        )
        if compile_result.returncode:
            raise TestFailure(
                "INTC source-extraction harness did not compile:\n"
                + compile_result.stdout
                + compile_result.stderr
            )
        run_result = subprocess.run(
            [str(binary)], cwd=root, check=False, text=True, capture_output=True
        )
        sys.stdout.write(run_result.stdout)
        sys.stderr.write(run_result.stderr)
        if run_result.returncode:
            raise TestFailure("INTC executable regression failed")

    print("PASS: production instruction-boundary wiring and save/reset contract")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except TestFailure as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
