#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""ROM-free regression for H8 watchdog interval-timer flag semantics.

The H8/3003 manual specifies two independent rules: OVF clears only after
software reads it as one and then writes zero, while interval mode requests an
interrupt at every TCNT overflow. This test extracts the relevant production
methods into a small type-compatible C++ harness and checks both rules.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


class TestFailure(RuntimeError):
    pass


def extract_method(source: str, qualified_name: str) -> str:
    match = re.search(
        rf"(?m)^[^\n]*\b{re.escape(qualified_name)}\s*\([^\n]*\)\s*(?:const\s*)?\{{",
        source,
    )
    if not match:
        raise TestFailure(f"production method not found: {qualified_name}")
    start = match.start()
    opening = source.find("{", match.start(), match.end())
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start : index + 1]
    raise TestFailure(f"unterminated production method: {qualified_name}")


def extract_table(source: str, declaration: str) -> str:
    start = source.find(declaration)
    if start < 0:
        raise TestFailure(f"production table not found: {declaration}")
    end = source.find(";", start)
    if end < 0:
        raise TestFailure(f"unterminated production table: {declaration}")
    return source[start : end + 1]


def make_shim(watchdog_cpp: str) -> str:
    tables = "\n".join(
        extract_table(watchdog_cpp, declaration)
        for declaration in (
            "const int h8_watchdog_device::div_bh[8]",
            "const int h8_watchdog_device::div_s [8]",
        )
    )
    methods = "\n\n".join(
        extract_method(watchdog_cpp, name)
        for name in (
            "h8_watchdog_device::tcnt_update",
            "h8_watchdog_device::wd_r",
            "h8_watchdog_device::wd_w",
        )
    )
    return f"""// Generated by h8_watchdog_state_test.py.
#include <cstdint>
#include <cstdlib>
#include <cstdio>

using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u64 = std::uint64_t;
using offs_t = std::uint32_t;

#define logerror(...) ((void)0)

class machine_stub
{{
public:
    class time_stub {{ public: const char *as_string() const {{ return "0"; }} }};
    bool side_effects_disabled() const {{ return false; }}
    time_stub time() const {{ return {{}}; }}
}};

class cpu_stub
{{
public:
    u64 cycles = 0;
    int updates = 0;
    int resets = 0;
    u64 total_cycles() const {{ return cycles; }}
    void internal_update() {{ updates++; }}
    void reset() {{ resets++; }}
}};

class intc_stub
{{
public:
    int requests = 0;
    int last_vector = -1;
    void internal_interrupt(int vector) {{ requests++; last_vector = vector; }}
}};

template <typename T> class device_ref
{{
public:
    explicit device_ref(T &device) : m_device(&device) {{}}
    T *operator->() {{ return m_device; }}
private:
    T *m_device;
}};

class h8_watchdog_device
{{
public:
    enum {{ B, H, S }};
    enum {{
        TCSR_CKS = 0x07, TCSR_NMI = 0x08, TCSR_TME = 0x20,
        TCSR_WT = 0x40, TCSR_OVF = 0x80
    }};

    h8_watchdog_device(cpu_stub &cpu, intc_stub &intc)
        : m_cpu(cpu), m_intc(intc) {{}}

    static const int div_bh[8];
    static const int div_s[8];
    device_ref<cpu_stub> m_cpu;
    device_ref<intc_stub> m_intc;
    int m_irq = 20;
    int m_type = H;
    u8 m_tcnt = 0;
    u8 m_tcsr = 0;
    u8 m_rst = 0;
    bool m_ovf_clear_armed = false;
    u64 m_tcnt_cycle_base = 0;
    machine_stub m_machine;

    machine_stub &machine() {{ return m_machine; }}
    void tcnt_update(u64 current_time = 0);
    u16 wd_r();
    void wd_w(offs_t offset, u16 data, u16 mem_mask = ~u16(0));
}};

{tables}

{methods}

static bool check(bool condition, const char *message)
{{
    if (!condition)
        std::fprintf(stderr, "FAIL: %s\\n", message);
    return condition;
}}

int main()
{{
    cpu_stub cpu;
    intc_stub intc;
    h8_watchdog_device timer(cpu, intc);
    bool ok = true;

    timer.wd_w(0, 0xa53c);
    timer.wd_w(0, 0x5aff);
    cpu.cycles = 256;
    timer.tcnt_update(cpu.cycles);
    ok &= check(intc.requests == 1, "first overflow did not request IRQ");
    ok &= check((timer.m_tcsr & 0x80) != 0, "first overflow did not set OVF");

    timer.wd_w(0, 0xa51c);
    ok &= check((timer.m_tcsr & 0x80) != 0,
                "write without prior OVF read incorrectly cleared OVF");
    timer.wd_w(0, 0xa53c);
    timer.wd_w(0, 0x5aff);
    cpu.cycles += 256;
    timer.tcnt_update(cpu.cycles);
    ok &= check(intc.requests == 2,
                "second overflow did not request IRQ while OVF remained set");
    ok &= check(intc.last_vector == 20, "wrong interval IRQ vector");

    (void)timer.wd_r();
    timer.wd_w(0, 0xa51c);
    ok &= check((timer.m_tcsr & 0x80) == 0,
                "read-one then write-zero did not clear OVF");

    if (ok)
        std::puts("PASS: H8 watchdog OVF clearing and repeated interval IRQs");
    return ok ? 0 : 1;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[2]
    )
    args = parser.parse_args()
    root = args.root.resolve()
    watchdog_cpp = (root / "src/devices/cpu/h8/h8_watchdog.cpp").read_text(
        encoding="utf-8"
    )
    compiler = shutil.which("c++") or shutil.which("clang++") or shutil.which("g++")
    if not compiler:
        raise TestFailure("no C++ compiler found")
    with tempfile.TemporaryDirectory(prefix="h8-watchdog-") as temp_name:
        temp = Path(temp_name)
        source = temp / "h8_watchdog_test.cpp"
        binary = temp / "h8_watchdog_test"
        source.write_text(make_shim(watchdog_cpp), encoding="utf-8")
        compile_result = subprocess.run(
            [compiler, "-std=c++17", "-Wall", "-Wextra", "-Werror",
             "-Wno-unused-parameter", str(source), "-o", str(binary)],
            cwd=root, check=False, text=True, capture_output=True,
        )
        if compile_result.returncode:
            raise TestFailure(compile_result.stdout + compile_result.stderr)
        run_result = subprocess.run(
            [str(binary)], cwd=root, check=False, text=True, capture_output=True
        )
        sys.stdout.write(run_result.stdout)
        sys.stderr.write(run_result.stderr)
        if run_result.returncode:
            raise TestFailure("watchdog executable regression failed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except TestFailure as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
